name: OpenVINO - Basic Test

on:
  workflow_dispatch:
  schedule:
    - cron:  '14 3 * * *'  #run every day at 3:14

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.10]
        os: [ubuntu-20.04]
        transformers: ['transformers', 'git+https://github.com/huggingface/transformers.git']
        optimum: ['optimum', 'git+https://github.com/huggingface/optimum.git']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[openvino,tests] ${{ matrix.optimum}} ${{ matrix.transformers }}
        
    - name: Test with Pytest
      run: |
        pytest tests/openvino/test_modeling_basic.py

