# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build and Test OpenVINO 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,] 
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Clone Openvino
      run: |
        git clone https://github.com/openvinotoolkit/openvino.git
    - name : Init OpenVINO
      run: |
        git submodule update --init --recursive && mkdir build
      working-directory: ./openvino
    - name: Build OpenVINO
      run: |
        pip install -r /home/runner/work/optimum-intel/optimum-intel/openvino/src/bindings/python/src/compatibility/openvino/requirements-dev.txt
        pip install -r /home/runner/work/optimum-intel/optimum-intel/openvino/src/bindings/python/wheel/requirements-dev.txt
        cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_INTEL_GPU=OFF -DENABLE_OPENCV=OFF -DENABLE_OV_ONNX_FRONTEND=ON -DENABLE_DOCS=OFF -DENABLE_SAMPLES=ON  -DENABLE_INTEL_MYRIAD=OFF -DCMAKE_INSTALL_PREFIX=/home/ubuntu/repos/openvino/install -DENABLE_INTEL_GNA=OFF -DENABLE_PYTHON=ON -DENABLE_WHEEL=ON -DENABLE_OV_TF_FRONTEND=OFF .. &&  make --jobs=$(nproc --all)
      working-directory: ./openvino/build
    - name: Install OpenVINO wheels
      run:
        pip install build/wheels/openvino*
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[openvino,nncf,tests]
    - name: Test with Pytest
      run: |
        pytest tests/openvino/ --ignore test_modeling_basic
