# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: OpenVINO - Test

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        transformers-version: ["4.41.*"]
    runs-on: [gasp, azure]
    container:
      image: cache-registry.caas.intel.com/cache/library/ubuntu:24.04

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "huggingface/optimum-intel"
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install PyTorch CPU version to avoid installing CUDA packages on GitHub runner without GPU
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install transformers==${{ matrix.transformers-version }}
        pip install .[openvino,openvino-tokenizers,tests,diffusers] onnxruntime
        pip install --upgrade nncf@git+https://github.com/openvinotoolkit/nncf.git@release_v2110
        pip install --upgrade --pre openvino openvino-tokenizers  --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/pre-release
    - name: Pip freeze
      run: |
        pip freeze
    - name: Test basic
      run: |
        pytest tests/openvino/test_modeling_basic.py --verbose
    - name: Test with Pytest
      run: |
        pytest tests/openvino/ --ignore tests/openvino/test_modeling_basic.py --durations=0
